### PR TITLE
CI: Use a centralized pathogen repo CI workflow

### PR DESCRIPTION
**Pull request by tsibley**
git ref of the branch should be updated to "master" before merge.

Related to #16.

### CODE REVIEW

**Comment by tsibley** [comment]
Marking this as draft since before merging this I want to:

- [ ] Merge https://github.com/nextstrain/.github/pull/13 (awaiting review)
- [ ]  Fixup branch ref in the workflow here from `trs/pathogen-repo-ci-workflows` to `master`

**Review by victorlin — APPROVED** [review]
Clean! Except `nextstrain/.github/.github` looks funny at first but that's fine.

**Comment by tsibley** [comment]
Yeah, it [got confused](https://github.com/nextstrain/zika/actions/runs/2079957986/workflow) when I tried to flatten it at first:

image

**Comment by tsibley** [comment]
(and there are [lots of other people doing the same thing](https://github.com/search?q=%22.github%2F.github%2Fworkflows%22&type=code))

**Pull request merged**
