### PR TITLE
Streamline snakefile

### LINKED ISSUE #5: Flatten data, results, auspice
I think it's unnecessary hierarchy to have:
```
build/
  - data/
  - results/
  - auspice/
```
I would flatten this to have `data/`, `results/` and `auspice/`. The intention would be that you could version `data/zika.fasta` if desired. Or drop in FASTAs. Or download via fauna.

### PR DESCRIPTION
**Pull request by trvrb**
Hi all. This is my attempt at a best practices snakefile. It differs somewhat from @tsibley's version of best practices. The base here is almost exactly `augur/builds/zika/Snakefile`. Relative to @tsibley's version, I've made the following changes:

#### 1. Remove use `field_map` to get `fasta_fields`

Even if this is inherited as a class, I think it's way overly complicated. Much simpler to just have a `fasta_fields` param in `download` and a `fasta_fields` param in `parse`. This makes it obvious what's going on and removes distracting boilerplate. This seemed too bespoke for a single use case of fauna vs augur parse as well.

#### 2. Remove `config.yaml` and move params to snakefile

I understand that `config.yaml` is commonly used for snakemake. And I did work with this a bunch, but I just couldn't see what we really gained from it. Whenever a rule needs updating it then adds redirection in going between the snakefile and `config.yaml`. I think better to have the parameters _right there_ in the rule. A single file with simple string parameters like `group_by = "country year month"` is less intimidating than two files and snakemake parameters `group_by = config['filter']['group_by']`.

I understand that having `config.yaml` allows overwriting with `config_local.yaml`, but I actually couldn't see this run that often. And the command line override of `snakemake --config filter.sequences_per_group=1` seemed too verbose to be really useful.

#### 3. Remove `credentials` from config

With this PR, the build now works by setting environment variables `RETHINK_HOST` and `RETHINK_AUTH_KEY`. These are referenced by fauna when running. The snakefile / config doesn't need to include them.

#### 4. Remove `:p` from shell script strings

I understand that `:p` is necessary to protect in the case of whitespace in file names. However, I am very comfortable with requiring that file names not include spaces.

#### 5. Flatten `data/`, `results/` and `auspice/`

Per issue #5. 

-------------------------------

I really wanted the nextstrain.org snakemake files to be super interpretable and a showcase for how builds are run.

I don't think all PRs need this much sign off, but it would be great if we could agree on this. Once we are in agreement, we can start copying out `nextstrain/tb`, `nextstrain/ebola`, etc...

_Closes #4, closes #5._

### CODE REVIEW

**Comment by jameshadfield** [comment]
See previous discussion on this topic [here](https://gist.github.com/tsibley/0e760b9f7d7955fc9d48ad87728a8af4)

I really like the informative messages printed by nextstrain/zika's snakefile (e.g. https://github.com/nextstrain/zika/blob/master/Snakefile#L169). Can we bring them back?

I agree with 1 & 5, my comment regarding 2 is [here](https://gist.github.com/tsibley/0e760b9f7d7955fc9d48ad87728a8af4#gistcomment-2633823), on point 4 i'm ambivalent. 

At the end of the day, this is our suggested template & how the tutorial will be written. People are free to construct their own snakemake structures, use another build system, or just run augur commands in the terminal ;)

**Comment by emmahodcroft** [comment]
Somehow after my initial comment on the [previous discussion](https://gist.github.com/tsibley/0e760b9f7d7955fc9d48ad87728a8af4) @jameshadfield references, I managed to miss all of the other comments - apologies!

To follow up a little, I certainly think users could figure out a `config.yaml` file and edit it - it's not insurmountable by any means - but I personally think it doesn't add much and does mean potentially flipping between two files if you're trying to modify to your own data, and just a little less transparency of how it ties together. And for a 'modular' `augur`, I think it's much easier to add and remove rules and modify the file names/paths and params accordingly if it's all in one file. 

I very much agree with @tsibley 's [last comment](https://gist.github.com/tsibley/0e760b9f7d7955fc9d48ad87728a8af4#gistcomment-2636179) to work towards `augur` writing `auspice_config.json` instead of having it be another rather opaque file to hand-modify (worse than `config.yaml`, I'd say, and shouldn't be the lower bar for file clarity). 

Point 4 I feel less strongly about, but I know I personally would go off Googling to find out what it was (to avoid breaking it). On the one hand this is maybe a good thing, as I'd learn something and best practices, as @tsibley [says](https://gist.github.com/tsibley/0e760b9f7d7955fc9d48ad87728a8af4#gistcomment-2632853), but on the other hand that means I'm not making progress on getting my data running in `augur`, which is what I came here to do :)

**Comment by jameshadfield** [comment]
re: `auspice_config.json` -- this can easily be put into the snakemake file and passed to `augur export` as command line flags, and I think i'm in favor of this. As a proof-of-principle, this is how the BEAST -> JSON script currently works:
```
python scripts/tree_to_JSON.py --nexus scratch/FFVPolFINALTest1.treesReduced.nex ... --maintainer "Simona Kraberger" "https://biodesign.asu.edu/people/simona-joop-kraberger" --title "Phylogeographic analysis of Feline Foamy Virus (FFV) in Colorado, USA" --defaults colorBy:location geoResolution:location ... --filters host location species sex age 
```

**Comment by trvrb** [comment]
> I really like the informative messages printed by nextstrain/zika's snakefile. Can we bring them back?

Commit 6f56415b18f40eed1be1e317c5b543d9df0162c0 does this.

**Comment by trvrb** [comment]
Thanks for the feedback @jameshadfield and @emmahodcroft. @huddlej and @rneher, do you have strong feelings here? Otherwise, I'm going to merge and continue to refine afterwards.

I'm now realizing it will be hard to have a house-style and I think that's okay. Each build should have a maintainer anyway and it will ultimately be their responsibility to make a snakefile that they are happy with.

**Comment by trvrb** [comment]
Okay. I think this has been up long enough to gather the feedback it's going to gather. I'm going to merge and we can continue to iterate.

**Comment by tsibley** [comment]
I must admit, I am disappointed by most of these changes and think overall they head us in a less robust direction. It is clear, however, that first-glance approachability is valued much more highly than I expected.

My thoughts on each change:

> 1. Remove use field_map to get fasta_fields — Even if this is inherited as a class, I think it's way overly complicated. Much simpler to just have a fasta_fields param in download and a fasta_fields param in parse.

Breaking this into two separate parameters hides the link that very much exists between them. The lists must match up and thus must be maintained together. Making explicit the field renaming was a goal of mine, and when separate, that side-effect is hidden to all but the most careful reader.

> 2. Remove config.yaml and move params to snakefile — I understand that having config.yaml allows overwriting with config_local.yaml, but I actually couldn't see this run that often.

Well, I was using a local config file on every run. I also used alternate config files specified with `snakemake --config=another.yaml` when testing various bits of the Snakefile. The benefits may not be as apparent for zika, but I expect that they'd be more apparent with a more complicated build like flu.

I think this hardcoding of parameter values is going to lead to people making local modifications to their Snakefile in development (to change `sequences_per_group` for example so the build runs faster), which will make it harder for them to pull in changes and make clean commits that don't include their local-only changes.

> 3. Remove credentials from config

Agreed that this is a change that should be made (see my comments on #4).

However, it does mean that building zika with `nextstrain build` is broken until environment passing is handled in some way.

> 4. Remove :p from shell script strings — I understand that :p is necessary to protect in the case of whitespace in file names. However, I am very comfortable with requiring that file names not include spaces.

This goes against basic tenets of robustness in software, and that's discouraging.

I expect that this will cause issues from time to time when people do put spaces, or any other shell metacharacter, into filenames and run into non-obvious problems. If we're lucky, we'll hear from them and be able to explain what's going on.

> 5. Flatten data/, results/ and auspice/

:+1:

**Pull request merged**
